import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assets/styles/globals.scss";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen"> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
